[book]
authors = ["Yollotl Tamayo"]
language = "es"
multilingual = false
src = "src"
title = "juezguapa"

[output.html]
mathjax-support = true
site-url = "/mdBook/"

[output.html.playground]
editable = true
line-numbers = true

[output.html.code.hidelines]
python = "~"
rust = "~"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
"/format/config.html" = "configuration/index.html"
